###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title":"Second title",
    "author":"Amrit P. Singh",
    "url":"localhost:3003",
    "likes":7
}

###
GET http://localhost:3003/api/blogs